// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

namespace ParkApi.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    [Migration("20200821213459_SeedData3")]
    partial class SeedData3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ParkName");

                    b.Property<int>("Rating");

                    b.Property<string>("State");

                    b.Property<string>("Type");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "Crater Lake inspires awe.",
                            ParkName = "Crater Lake National Park",
                            Rating = 5,
                            State = "Oregon",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "There are seven developed fee-site campgrounds, managed on a first-come, first-served basis",
                            ParkName = "Tillamook State Forest",
                            Rating = 5,
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "The stunning beauty and abundant wildlife and plants found here have drawn humans to this place for more than 11,000 years",
                            ParkName = "Grand Teton National Park",
                            Rating = 5,
                            State = "Wyoming",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "The park comprises wooded country overlooking the Hudson and Piermont Marsh.",
                            ParkName = "Tallman Mountain State Park",
                            Rating = 4,
                            State = "New York",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
                            ParkName = "Glacier National Park",
                            Rating = 5,
                            State = "Montana",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "Crater Lake inspires awe.",
                            ParkName = "Crater Lake National Park",
                            Rating = 5,
                            State = "Oregon",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 7,
                            Description = "There are seven developed fee-site campgrounds, managed on a first-come, first-served basis",
                            ParkName = "Tillamook State Forest",
                            Rating = 5,
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 8,
                            Description = "The stunning beauty and abundant wildlife and plants found here have drawn humans to this place for more than 11,000 years",
                            ParkName = "Grand Teton National Park",
                            Rating = 5,
                            State = "Wyoming",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 9,
                            Description = "The park comprises wooded country overlooking the Hudson and Piermont Marsh.",
                            ParkName = "Tallman Mountain State Park",
                            Rating = 4,
                            State = "New York",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 10,
                            Description = "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
                            ParkName = "Glacier National Park",
                            Rating = 5,
                            State = "Montana",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 11,
                            Description = "Crater Lake inspires awe.",
                            ParkName = "Crater Lake National Park",
                            Rating = 5,
                            State = "Oregon",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 12,
                            Description = "There are seven developed fee-site campgrounds, managed on a first-come, first-served basis",
                            ParkName = "Tillamook State Forest",
                            Rating = 5,
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 13,
                            Description = "The stunning beauty and abundant wildlife and plants found here have drawn humans to this place for more than 11,000 years",
                            ParkName = "Grand Teton National Park",
                            Rating = 5,
                            State = "Wyoming",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 14,
                            Description = "The park comprises wooded country overlooking the Hudson and Piermont Marsh.",
                            ParkName = "Tallman Mountain State Park",
                            Rating = 4,
                            State = "New York",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 15,
                            Description = "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
                            ParkName = "Glacier National Park",
                            Rating = 5,
                            State = "Montana",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 16,
                            Description = "Crater Lake inspires awe.",
                            ParkName = "Crater Lake National Park",
                            Rating = 5,
                            State = "Oregon",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 17,
                            Description = "There are seven developed fee-site campgrounds, managed on a first-come, first-served basis",
                            ParkName = "Tillamook State Forest",
                            Rating = 5,
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 18,
                            Description = "The stunning beauty and abundant wildlife and plants found here have drawn humans to this place for more than 11,000 years",
                            ParkName = "Grand Teton National Park",
                            Rating = 5,
                            State = "Wyoming",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 19,
                            Description = "The park comprises wooded country overlooking the Hudson and Piermont Marsh.",
                            ParkName = "Tallman Mountain State Park",
                            Rating = 4,
                            State = "New York",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 20,
                            Description = "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
                            ParkName = "Glacier National Park",
                            Rating = 5,
                            State = "Montana",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 21,
                            Description = "Crater Lake inspires awe.",
                            ParkName = "Crater Lake National Park",
                            Rating = 5,
                            State = "Oregon",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 22,
                            Description = "There are seven developed fee-site campgrounds, managed on a first-come, first-served basis",
                            ParkName = "Tillamook State Forest",
                            Rating = 5,
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 23,
                            Description = "The stunning beauty and abundant wildlife and plants found here have drawn humans to this place for more than 11,000 years",
                            ParkName = "Grand Teton National Park",
                            Rating = 5,
                            State = "Wyoming",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 24,
                            Description = "The park comprises wooded country overlooking the Hudson and Piermont Marsh.",
                            ParkName = "Tallman Mountain State Park",
                            Rating = 4,
                            State = "New York",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 25,
                            Description = "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
                            ParkName = "Glacier National Park",
                            Rating = 5,
                            State = "Montana",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 26,
                            Description = "Crater Lake inspires awe.",
                            ParkName = "Crater Lake National Park",
                            Rating = 5,
                            State = "Oregon",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 27,
                            Description = "There are seven developed fee-site campgrounds, managed on a first-come, first-served basis",
                            ParkName = "Tillamook State Forest",
                            Rating = 5,
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 28,
                            Description = "The stunning beauty and abundant wildlife and plants found here have drawn humans to this place for more than 11,000 years",
                            ParkName = "Grand Teton National Park",
                            Rating = 5,
                            State = "Wyoming",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 29,
                            Description = "The park comprises wooded country overlooking the Hudson and Piermont Marsh.",
                            ParkName = "Tallman Mountain State Park",
                            Rating = 4,
                            State = "New York",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 30,
                            Description = "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes.",
                            ParkName = "Glacier National Park",
                            Rating = 5,
                            State = "Montana",
                            Type = "National"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
